Add Workflows and Issue template
adobe/generator-add-publish-events pull request #1
Opened 2023-08-14 07:48 UTC by sangeetha5491

## Description

Add workflows for publish to npm
Add issue template
Add pull request template

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-14 10:43 UTC, moritzraho submitted a review, later dismissed

2023-08-16 05:15 UTC, sangeetha5491 commented
@shazron request you to kindly review the workflows as suggested by @moritzraho

2023-08-16 08:41 UTC, shazron requested changes

2023-08-16 08:41 UTC, shazron commented on .github/workflows/daily.yml
> +        node-version: [14]
might as well make this either the latest or node-16, since 14 is EOL now

2023-08-16 08:41 UTC, shazron commented on .github/workflows/node.js.yml
> +        run: curl -s https://codecov.io/bash | bash
this should be using the codecov github action, see example in the app plugin workflow

2023-08-16 08:41 UTC, shazron commented on .github/workflows/on-push-publish-to-npm.yml
> +          node-version: 14
might as well make this either the latest or node-16, since 14 is EOL now

2023-08-16 08:41 UTC, shazron commented on .github/workflows/prerelease.yml
> +        uses: adobe/update-prerelease-npm-version@v1.0.0
let's use v1.1.0 which is the latest

2023-08-16 08:41 UTC, shazron commented on .github/workflows/version-bump-publish.yml
> +          node-version: 14
might as well make this either the latest or node-16, since 14 is EOL now

2023-08-16 11:29 UTC, shazron approved these changes

2023-08-16 11:38 UTC, merged